version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/gestion_de_projets
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
